#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 ft=python

# author : Prakash [प्रकाश]
# date   : 2019-07-14 08:07

import click

from asctouni.converter import Converter

def asciitouni(infile,outfile,*args,**kwargs):
    CVT = Converter()
    conv_str = ''
    with open(infile,'r') as ifl:
        for line in ifl:
            line_uni = CVT.convert_preeti(line)
            conv_str += line_uni

    with open(outfile,'w') as ofl:
        ofl.write(conv_str)
    print('Written file ',outfile) 



@click.command ()
@click.option ('-i', '--infile', type=str,help='input file name')
@click.option ('-o', '--outfile', type=str, help='output file name')
@click.option ('-d', '--input-dir',type=str,help='output directory default .')
@click.option ('-a', '--action',type=str,help=' action to perform')

def process_request(infile,outfile,action,*args,**kwargs):
    if action == 'asctouni':
        asciitouni(infile,outfile,*args,**kwargs)


if __name__ == '__main__':
    process_request()


